### ISSUE TITLE
Adicionar um item "Como contribuir" no menu do site

### ISSUE THREAD

**Issue by taniaa** [pyladies-brazil/br-pyladies#15]
Desta forma, como falei com a Gabriela, fica mais fácil do pessoal enviar as modificações para o site, como novo post, novo evento, nova líder da sua cidade. Além de juntar materiais como estes:
https://www.gitbook.com/book/brazilpyladies/handbook/details
http://brasil.pyladies.com/hangouts/2015/02/09/como-comecar-um-grupo-pyladies/

**Comment by erichideki** [comment]
Repliquei um artigo que a Gabi fez no site, dessa forma o pessoal poderá criar a Pyladies em sua região.

**Comment by aninhalacerda** [comment]
@erichideki Acho q a ideia é criar um link para esse post no menu principal. Assim sempre vai ter um fácil acesso pela página principal

**Comment by erichideki** [comment]
@aninhalacerda Question Dummie: Como faço para criar um novo link no Jekyll? Procurei algumas alternativas pela net, testei e não consegui.

Digo, o link e auto'magicamente' já ir direto para o menu.

Dessa forma abro uma aba sobre como ajudar e colocar outra com os vídeos.

**Comment by aninhalacerda** [comment]
@erichideki, there's no dummy question :) 
Para criar um novo link no menu você precisa alterar o arquivo _config.yml na parte de "links" e criar uma página com o mesmo nome que você definiu no atributo 'url' desse arquivo. Você pode dar uma olhada em modelos das outras páginas (events, locations, ladies...)

Bom, no momento estamos trabalhando para começar uma migração do nosso site para uma plataforma em Python (Pelican) - o site foi migrado pelo pessoal de Curitiba e nós vamos incorporar ao repositório principal. Minha sugestão é que você não faça nenhuma mudança grande por aqui agora, e se quiser dar uma olhada na nova estrutura - https://github.com/pyladies-curitiba/br-pyladies-pelican. Hoje a noite ou amanhã já devemos ter um fork do novo repositório por aqui e novas issues criadas lá para ajudar na migração. 

Sua ajuda é muito bem vinda.

**Comment by aninhalacerda** [comment]
moved to [issue #10 on new repo](https://github.com/pyladies-brazil/br-pyladies-pelican/issues/10)
