### ISSUE TITLE
Trocar vídeos por embed do YouTube

### ISSUE THREAD

**Issue by taniaa** [pyladies-brazil/br-pyladies#16]
Hoje exige um plugin pra ver o vídeo (ver imagem anexa) na home. O ideal é embedar o vídeo do YouTube na home do site. Talvez até criar uma sessão de vídeos no site.

Vídeos atuais:
- Fernando Masanori: https://www.youtube.com/watch?v=5M9iFmMqcmc
- Lynn Root: https://www.youtube.com/watch?v=4oHw6LcViMI
- Selena Deckelmann: https://www.youtube.com/watch?v=QeFqUjSD7Jw
- Jessica McKellar (Engenheira no Dropbox e Diretora da Python Software Foundation), na PythonNordeste 2015: https://www.youtube.com/watch?v=WMM9qCUyH6A
- Canal da Brazil PyLadies: https://www.youtube.com/channel/UCzFDzkgQ3mWNvcHoTVcT2bg

![captura de tela 2015-07-10 as 17 01 14](https://cloud.githubusercontent.com/assets/1102067/8628298/1e14fd30-2728-11e5-9e7e-e4c425e61834.png)

**Comment by erichideki** [comment]
Esse problema é no navegador, que por padrão 'bloqueia' vídeos em Flash.

Quanto aos outros vídeos, já foram adicionados no último PR feito.

**Comment by taniaa** [comment]
Oi, @erichideki.

No site ainda constam apenas 3 vídeos na home (com problema de plugin no browser) e não tem uma área nova de VÍDEOS, só tem Sobre, Blog, Eventos, Locais e Ladies.

Acredito que depois que o site for atualizado poderemos ver se a issue estará concluída :)

PS: é bom lembrar que os grandes buscadores já nem consideram Flash... 
![captura de tela 2015-09-02 as 11 27 03](https://cloud.githubusercontent.com/assets/1102067/9633964/c0453568-5165-11e5-8ba4-d785991c8be3.png)

**Comment by aninhalacerda** [comment]
Foi criada uma nova issue para criar a sessão de vídeos (https://github.com/pyladies-brazil/br-pyladies-pelican/issues/11)
