### ISSUE TITLE
Criar campo com link do site de cada cidade que tem pyladies, em locations.yml

### ISSUE THREAD

**Issue by taniaa** [pyladies-brazil/br-pyladies#17]
Adicionar campo para link/site. Se tiver link/site linkar no logo da cidade, senão deixar sem link.

Hoje só linka para a página locations.

https://github.com/pyladies-brazil/br-pyladies/blob/master/_data/locations.yml

**Comment by eduardohitek** [comment]
@taniaa acho que pode fechar Issue, baseado na PR #19

**Comment by taniaa** [comment]
Mas ainda não está ok em produção: http://brazil.pyladies.com/locations

Continua linkando para location...

**Comment by taniaa** [comment]
@aninhalacerda será que a rotina automatizada está com problema?

Aparentemente está tudo certo com o código:
https://github.com/pyladies-brazil/br-pyladies/blob/master/locations.html
https://github.com/pyladies-brazil/br-pyladies/blob/master/_data/locations.yml

**Comment by aninhalacerda** [comment]
@taniaa o passo para ir a produção não é automático. 
Uma vez feito um commit, o código é deployado em staging (https://staging-brasilpyladies.herokuapp.com/) e alguém precisa verificar se está tudo ok. Se estiver pronto para subir a producão, qualquer uma de nós aqui pode clicar no 'play' para o proximo step aqui: https://snap-ci.com/pyladies-brazil/br-pyladies/branch/master

**Comment by aninhalacerda** [comment]
@taniaa @eduardohitek pelo que verifiquei em staging, os links para twitter e facebook estão na página mas não estão aparecendo.

Podem dar uma olhada lá ? https://staging-brasilpyladies.herokuapp.com/locations

**Comment by aninhalacerda** [comment]
O problema era com o include do font-awesome css:

<img width="1267" alt="screen shot 2015-07-14 at 11 22 27 am" src="https://cloud.githubusercontent.com/assets/626988/8675747/081a79be-2a1c-11e5-8e98-32a9cbc73bc6.png">

Já fiz um commit para corrigir.

Podem conferir em prod (http://brazil.pyladies.com/locations) e fechar a issue se já estiver tu ok?

**Comment by eduardohitek** [comment]
Legal @aninhalacerda! Era só isso mesmo... Obrigado!
BTW: Manda um abraço para o Tomás. :grinning:

**Comment by aninhalacerda** [comment]
heheheheh, mando sim @eduardohitek.
e obrigada pela contribuição :)

**Comment by taniaa** [comment]
Legal @aninhalacerda e @eduardohitek! O ideal era não ter link (tag <a href="" target="_blank">) no logo ou no título quando não informado (ao invés de fazer link para a própria página /location). 

Mas fazer o link funcionar quando informado, já foi bom :)
