### ISSUE TITLE
Informar a cidade das líderes de cada grupo

### ISSUE THREAD

**Issue by taniaa** [pyladies-brazil/br-pyladies#18]
Temos 5 cidades no Brasil e 7 líderes dos grupos.

Seria interessante informar a cidade de cada líder aqui:
http://brazil.pyladies.com/ladies

**Comment by aninhalacerda** [comment]
moved to [issue #9 on new repo](https://github.com/pyladies-brazil/br-pyladies-pelican/issues/9)
