### ISSUE TITLE
Site Pyladies usando Pelican

### ISSUE THREAD

**Issue by ellisonleao** [pyladies-brazil/br-pyladies#22]
Olá meninas!

Primeiramente parabéns pelo trabalho! Faço parte do grupy-pr aqui em Curitiba e vi que o site de vocês usava Jekyll e resolvi criar uma versão usando Pelican. Estamos organizando o pyladies-curitiba e um dos projetos foi reescrever ele em pelican.  Hoje o repositório está em https://github.com/pyladies-curitiba/br-pyladies-pelican

Gostaria de saber se vocês não querem dar continuidade com ele e usar ele como repositório oficial, já que ele usa uma ferramenta python.  Por favor, me digam o que acham. 

Obrigado!

**Comment by gabicavalcante** [comment]
@ellisonleao!!! que show, cara!!! Desculpa a demora em responder, mas eu fiquei muito feliz com o projeto :) a gente usa o jekyll por uma certa praticidade que a ferramenta nos dá, mas essa versão com python é incrível. To aqui louca de felicidade olhando o código, vou falar com as meninas agora mesmo :D

**Comment by gabicavalcante** [comment]
@ellisonleao, preciso nem dizer o quanto o projeto foi amado pelas meninas, vamos começar a migração essa semana mesmo. Como algumas coisas foram mudadas no outro site, nós faremos um fork, vamos atualizando, e quando tiver ok vai direto para produção

**Comment by aninhalacerda** [comment]
@ellisonleao @I-am-Gabi Ficou muito show mesmo! Vou começar a migração para ser nosso site oficial logo logo :)

obrigada.

**Comment by ellisonleao** [comment]
@I-am-Gabi @aninhalacerda Obrigado meninas! Se precisarem de ajuda, não hesitem em me pingar. Estou à disposição!

**Comment by erichideki** [comment]
Irei mandar um PR daqui alguns minutos atualizando com os últimos PR's que mandei. Aí fica com a @aninhalacerda a parte de colocar em produção, por favor. O Pelican não gosta de mim quando o assunto é deploy =(

**Comment by aninhalacerda** [comment]
@erichideki acabei de fazer um fork para a nossa organização (https://github.com/pyladies-brazil/br-pyladies-pelican), manda os PR's lá :)

Vou criar as issues que faltam hoje a noite e migrar o processo de deploy no Snap depois disso.

e muito obrigada pelas contribuições ( @ellisonleao , @erichideki )

**Comment by ellisonleao** [comment]
No caso, o site do pelican usa o próprio github pages para servir o conteúdo, então o processo de deploy é bem simples e só precisa do comando

```
make github
```

onde ele já faz o push do conteúdo rendererizado atual na branch `gh-pages` . Único problema seria usar essa branch no fork do projeto no `pyladies` global.

**Comment by aninhalacerda** [comment]
o jekyll também usa o github pages para servir conteúdo. O problema é que o nosso domínio (brasil.pyladies.com) é gerenciado pelo PyLadies San Francisco e para colocar o site no ar temos acesso a conta do heroku. Mas não foi difícil colocar o jekyll lá, acredito que com o Pelican tb vai ser simples.

E dessa forma podemos continuar com o esquema de ter uma versão em staging (staging-brasilpyladies.herokuapp.com) onde podemos conferir e testar algumas coisas antes de colocar em produção.

**Comment by aninhalacerda** [comment]
outra opção seria conversar com as meninas de SF e apontar o CNAME do nosso projeto para o brasil.pyladies.com e pedir para que elas configurem lá o que precisar. 

E a questão do staging podemos pensar em alguma outra solução.

**Comment by ellisonleao** [comment]
vocês podem modificar o `Makefile` para enviar o staging direto pro heroku, usando o heroku toolbelt mesmo. Se o pessoal de CF puder usar o CNAME do github facilitaria bastante.

**Comment by aninhalacerda** [comment]
ah, esqueci de dizer que nosso deploy para produção hoje é independente daquele código no diretório 'brazil' no repositório do pyladies global. O nosso código aqui vai direto para o heroku quando fazemos deploy no Snap já que elas nos deram permissão para isso.

Hoje a noite vou olhar umas possíveis soluções. :)

**Comment by ellisonleao** [comment]
Show! se precisarem de algo, me avisem! :smile:

**Comment by erichideki** [comment]
Por favor, depois deem um "git pull origin master" no repositório do pessoal de Curitiba. Minhas PR's acidentalmente foram pra lá. My bad.

Nelas atualizei as informações que havia feito. Ainda é preciso abrir uma página para os vídeos e como colaborar. Tentei fazer o esquema que o @ellisonleao colocou no README mas não deu certo.

**Comment by ellisonleao** [comment]
@erichideki você tentou só dar o `make github` ?  Qual foi o problema que você teve?

**Comment by erichideki** [comment]
@ellisonleao Não entendo muito bem o que o Pelican precisa para criar automaticamente uma página nova, e ela já ser listada também no menu. Mas é mais falha minha, tenho que entender melhor esse 'pássaro'.

**Comment by ellisonleao** [comment]
@erichideki O que você quer dizer quando fala `criar automaticamente` ? Tem um comando que gera um `.md` na pasta `content` do projeto para uma nova página `make newpage` . Dae é só colocar o conteúdo nessa nova página.  Você pode seguir o exemplo das outras páginas para ter uma idéia, se não quiser usar o comando do Makefile.
