### ISSUE TITLE
O SnapCI realmente está fazendo o deploy contínuo?

### ISSUE THREAD

**Issue by erichideki** [pyladies-brazil/br-pyladies#25]

**Comment by aninhalacerda** [comment]
@erichideki o snap faz deploy contínuo para uma URL de staging (http://staging-brasilpyladies.herokuapp.com/ ). Depois de verificar as mudanças lá precisamos iniciar o deploy para produção manualmente no snap.

**Comment by erichideki** [comment]
Entendi. Muito obrigado Ana. :+1:
