### ISSUE TITLE
Missing PyLadies Brasil logo on header

### ISSUE THREAD

**Issue by aninhalacerda** [pyladies-brazil/br-pyladies#3]
There's nothing that indicates we are in a PyLadies Brasil page. It would be good to have a new logo to put on the header.

**Comment by taniaa** [comment]
Seria interessante identificar o Brazil E deixar o logo maior :)

**Comment by erichideki** [comment]
Deixei o logo um pouco maior, mas trocar um logo com o 'Brasil' embaixo seria bacana. Minhas habilidades de design infelizmente não permitem que faça isso.

**Comment by taniaa** [comment]
@erichideki vc está alterando onde? O site continua da mesma forma.

Para mexer no logo e por Brasil, @erichideki  @aninhalacerda pode me mandar o arquivo fonte que faço uma proposta, por favor?
![captura de tela 2015-09-02 as 11 35 17](https://cloud.githubusercontent.com/assets/1102067/9634162/ccacee8a-5166-11e5-9728-f7d0d6606e67.png)

**Comment by aninhalacerda** [comment]
foi criada uma nova issue no novo projeto (https://github.com/pyladies-brazil/br-pyladies-pelican/issues/12)
